name: Docker Build and Push

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]

jobs:
  build:
    runs-on: ubuntu-latest   # Use Ubuntu virtual machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ashish2210ashish/rider-co:latest
